redis:
  host: '127.0.0.1'
  post: '6379'
  timeout: 5000
  channels:
    fromBBBApps: 'bigbluebutton:from-bbb-apps:*'
    toBBBApps:
      pattern: 'bigbluebutton:to-bbb-apps:*'
      chat: 'bigbluebutton:to-bbb-apps:chat'
      captions: 'bigbluebutton:to-bbb-apps:caption'
      meeting: 'bigbluebutton:to-bbb-apps:meeting'
      presentation: 'bigbluebutton:to-bbb-apps:presentation'
      users: 'bigbluebutton:to-bbb-apps:users'
      voice: 'bigbluebutton:to-bbb-apps:voice'
      whiteboard: 'bigbluebutton:to-bbb-apps:whiteboard'
      polling: 'bigbluebutton:to-bbb-apps:polling'
